#!/bin/bash

export XTPE_LINK_TYPE=dynamic
export CRAYPE_LINK_TYPE=dynamic

module load cray-hdf5-parallel


# recipe for:
P=boost
V=1_68_0
export DOWNLOADS_DIR="/global/project/projectdirs/m669/nneveu/opal_builds/nersc"
mkdir -p "$DOWNLOADS_DIR/$P-$V"
export SRC_DIR="$DOWNLOADS_DIR/$P-$V"
 
# download
#curl -L \
#    --output "${DOWNLOADS_DIR}/${P}_$V.tar.gz" \
#    "https://netcologne.dl.sourceforge.net/project/$P/$P/${V//_/.}/${P}_$V.tar.gz"

# unpack
mkdir -p "${SRC_DIR}" && cd "$_"
tar xvf "${DOWNLOADS_DIR}/${P}_$V.tar.gz"

# configure
mkdir -p "${SRC_DIR}/build"
cd "${SRC_DIR}/${P}_$V"
./bootstrap.sh \
#    --prefix="${PREFIX}" \
    --with-libraries=all

## compile & install
#./b2 \
#    --build-type=minimal \
#    --build-dir=""${SRC_DIR}/$P/build"" \
#    --layout=system \
#    --without-mpi \
#    variant=release \
#    link=shared,static \
#    threading=multi \
#    stage
#./b2 \
#    --build-type=minimal \
#    --build-dir=""${SRC_DIR}/$P/build"" \
#    --layout=system \
#    --without-mpi \
#    variant=release \
#    link=shared,static \
#    threading=multi \
#    install
#


