#!/bin/bash

export XTPE_LINK_TYPE=dynamic
export CRAYPE_LINK_TYPE=dynamic

module load cray-hdf5-parallel


# recipe for:
P=boost
V=1_68_0
export PREFIX="/global/homes/n/nneveu/boost-1.68"
export DOWNLOADS_DIR="/global/homes/n/nneveu/opal_builds/nersc"
mkdir -p "$DOWNLOADS_DIR/$P-$V"
export SRC_DIR="$DOWNLOADS_DIR/$P-$V"

# download
#curl -L \
#    --output "${DOWNLOADS_DIR}/${P}_$V.tar.gz" \
#    "https://netcologne.dl.sourceforge.net/project/$P/$P/${V//_/.}/${P}_$V.tar.gz"

# unpack
#mkdir -p "${SRC_DIR}" && cd "$_"
#tar xvf "${DOWNLOADS_DIR}/${P}_$V.tar.gz"

# configure
mkdir -p "${SRC_DIR}/build"
cd "${SRC_DIR}/${P}_$V"

./bootstrap.sh \
        --prefix="${PREFIX}"  \
       --with-toolset=gcc \
        --without-libraries=python  


# compile & install
#./b2 --build-type=minimal --build-dir=""${SRC_DIR}/build""  --layout=system --without-python toolset=gcc variant=release link=shared,static threading=multi install -j 3





