#!/bin/bash

#Current modules that are working
#nneveu@cori02:/global/u1/n/nneveu/software/opal_builds/nersc> module list 
#Currently Loaded Modulefiles:
#  1) modules/3.2.10.6                                 10) udreg/2.3.2-6.0.7.1_5.13__g5196236.ari           19) rca/2.2.18-6.0.7.1_5.47__g2aa4f39.ari
#  2) nsg/1.2.0                                        11) ugni/6.0.14.0-6.0.7.1_3.13__gea11d3d.ari         20) atp/2.1.3
#  3) craype-haswell                                   12) pmi/5.0.14                                       21) PrgEnv-gnu/6.0.4
#  4) craype-network-aries                             13) dmapp/7.1.1-6.0.7.1_5.45__g5a674e0.ari           22) cmake/3.3.2
#  5) craype/2.5.15                                    14) gni-headers/5.0.12.0-6.0.7.1_3.11__g3b1768f.ari  23) cray-hdf5-parallel/1.10.2.0
#  6) cray-mpich/7.7.3                                 15) xpmem/2.2.15-6.0.7.1_5.11__g7549d06.ari          24) gsl/2.1
#  7) tmux/2.2                                         16) job/2.2.3-6.0.7.1_5.43__g6c4e934.ari             25) boost/1.67.0
#  8) altd/2.0                                         17) dvs/2.7_2.2.118-6.0.7.1_10.1__g58b37a2           26) gcc/6.1.0
#  9) cray-libsci/18.07.1                              18) alps/6.6.43-6.0.7.1_5.45__ga796da32.ari

export XTPE_LINK_TYPE=dynamic
export CRAYPE_LINK_TYPE=dynamic

module switch PrgEnv-intel/6.0.4 PrgEnv-gnu
#1. Load dependancies (software that opal needs):
module load cmake 
module remove darshan
module load cray-hdf5-parallel
#module load h5hut-parallel #Using H5hut build in software dir
module load gsl   
module load boost #/1.67.0 
module load gcc #/6.1.0 #This version needed for specific c++11 support?


export SOFTWARE="/global/homes/n/nneveu/software"
export PATH="$SOFTWARE/H5hut-2.0.0rc4/:${PATH}"   #/opal_builds/nersc/H5hut-2.0.0rc4/:${PATH}"
export H5HUT_HOME=$SOFTWARE/H5hut-2.0.0rc4
export H5HUT_PREFIX=$H5HUT_HOME
export H5HUT_DIR=$H5HUT_HOME
export H5HUT_INCLUDE_DIR=$H5HUT_HOME/include
export H5HUT_LIBRARY_DIR=$H5HUT_HOME/lib

#export BOOST_HOME=$SOFTWARE/boost-1.68
#export BOOST_DIR=$BOOST_HOME
#export BOOST_PREFIX=$BOOST_HOME
#export BOOST_INCLUDE_DIR=$BOOST_HOME/include
#export BOOST_LIBRARY_DIR=$BOOST_HOME/lib
#export BOOST_ROOT=$NHOME/boost_1_62_0_build/

#2. Point to the cray compiler wrappers (icc and icpc)
I_MPI_CC=cc;I_MPI_CXX=CC;I_MPI_F90=ftn;I_MPI_F77=ftn
export I_MPI_CC I_MPI_CXX I_MPI_F90 I_MPI_F77
#
CC=cc;CXX=CC;F90=ftn;F77=ftn
export CC CXX F90 F77

#Note: Steps #1 and #2 can be done by sourcing this file: 
# > source opal_build_cori

#Steps #3-6 should be done on the command line:

#3. Download a copy of the opal source code.
#This step can be skipped if you already have a copy of the opal src.
# > git clone https://gitlab.psi.ch/OPAL/src.git

#3.b If you have a copy of src already, make sure it is up to date
# > cd /src
# > git pull #(while in the opal /src directory)

#4. Make a build directory in the opal src directory
# > mkdir build #(while in /src from step #3.b)
# > cd build 

#Note: this directory will stay in place indefinitely.
# If you build opal again, you do not need to make a new build directory.
# Before a second build, I recommend taring the build dir (with a date in the name), 
# move the tarfile somewhere safe (storage), then delete the build dir contents.
# This way cmake will save files to an empty directory every time.

#5. Run cmake to configure build
# Note: change the path to where you want the opal executable to be installed
#cmake -DCMAKE_INSTALL_PREFIX=/home/neveu/software .. 

#6. Run make and install to generate executables
# > make -j 8 
# > make install

####################################################################
###################################################################
# Build steps from NERSC
# 1. load modules from above
 
#####cd /global/project/projectdirs/m669/nneveu/opal_builds/nersc/src
#####sed -i "s/GSL_LIBRARY gsl/GSL_LIBRARY libgsl.a/g; s/GSL_CBLAS_LIBRARY gslcblas/GSL_CBLAS_LIBRARY libgslcblas.a/g" CMakeModules/FindGSL.cmake
##### 
#####mkdir build.intel_gcc7
#####cd build.intel_gcc7
#####cmake -DCMAKE_INSTALL_PREFIX=/global/project/projectdirs/m669/nneveu/opal/2.1.0_gcc7 ..
 
#make -j8
#make install 

