#!/bin/bash

module load intel-parallel-studio/cluster.2017.4-wyg4gfu
module load hdf5/1.10.1-n3h76ta

# recipe for:
P=H5hut
V=${H5HUT_VERSION:-2.0.0rc6}

export DOWNLOADS_DIR="/lcrc/project/MCS-SLAC/software/opal/$P"
mkdir -p "$DOWNLOADS_DIR/"
export SRC_DIR="$DOWNLOADS_DIR/"
export PREFIX="$DOWNLOADS_DIR/"

FNAME="$P-$V.tar.gz"
DOWNLOAD_URL="http://amas.web.psi.ch/Downloads/$P/${FNAME}"
SRC_FILE="${DOWNLOADS_DIR}/${FNAME}"

# download
test -r "${SRC_FILE}" || curl -L --output "$_" "${DOWNLOAD_URL}"

# unpack
mkdir -p "${SRC_DIR}/" && cd "$_"
tar xvf "${SRC_FILE}"
cd "${SRC_DIR}/$P-$V"
./autogen.sh || exit 1

CC=mpiicc;CXX=mpiicpc;F90=ifort;F77=ifort
export CC CXX F90 F77

# configure
mkdir -p "${SRC_DIR}/build" && cd "$_"
CC=mpiicc CXX=mpiicpc "${SRC_DIR}/$P-$V/configure" \
        --prefix="${PREFIX}" \
        --enable-shared \
        --enable-parallel \
        --with-pic
# compile and install
#make -j ${NJOBS}
#make install




